### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by bhrigu123** [bhrigu123/Instant-Lyrics#1]
![il](https://cloud.githubusercontent.com/assets/6123105/23824316/3fe58044-069a-11e7-804e-180ea4041002.jpeg)

![il-ss](https://cloud.githubusercontent.com/assets/6123105/23824317/4735e83e-069a-11e7-8b1e-2814632bb3aa.jpeg)

![il](https://cloud.githubusercontent.com/assets/6123105/23824730/e0e0829e-06a1-11e7-8d57-3235c4266f2c.gif)

**Comment by akhilesh-k** [comment]
Which distribution is this on your pc? Looks quite interesting!

**Comment by bhrigu123** [comment]
I'm using:
OS: Elementary OS 0.4 Loki
Plank theme: Shade
