### ISSUE TITLE
Follow PEP 8

### ISSUE THREAD

**Issue by yasoob** [bhrigu123/Instant-Lyrics#2]
Hey nice project! One small issue though. You should use PEP 8 style guide when programming in Python. This also includes using spaces in place of tabs. :)

**Comment by bhrigu123** [comment]
Thanks for the tip @yasoob . Will definitely look into it. :)

**Comment by bhrigu123** [comment]
5cee5e89b7ef2153150bcf4e2f92998504c2af7d
